export enum UserRole {
  ADMIN_SYSTEM = 'ADMIN_SYSTEM',
  DGCMP = 'DGCMP',
  AGENT_DGCMP = 'AGENT_DGCMP',
  PPM = 'PPM',
  AGENT_PPM = 'AGENT_PPM',
  MEMBRE_COMMISSION = 'MEMBRE_COMMISSION',
  OPERATEUR_ECONOMIQUE = 'OPERATEUR_ECONOMIQUE',
  ARMP = 'ARMP',
  AGENT_ARMP = 'AGENT_ARMP',
  DNCMP = 'DNCMP',
  PUBLIC = 'PUBLIC',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING = 'PENDING',
}

export enum OrganizationType {
  AUTORITE_CONTRACTANTE = 'AUTORITE_CONTRACTANTE',
  OPERATEUR_ECONOMIQUE = 'OPERATEUR_ECONOMIQUE',
  ARMP = 'ARMP',
  DNCMP = 'DNCMP',
  DGCMP = 'DGCMP',
  MINISTERE = 'MINISTERE',
  AUTRE = 'AUTRE',
}

export enum DACStatus {
  BROUILLON = 'BROUILLON',
  PUBLIE = 'PUBLIE',
  EN_COURS = 'EN_COURS',
  CLOTURE = 'CLOTURE',
  ATTRIBUE = 'ATTRIBUE',
  ANNULE = 'ANNULE',
  INFRUCTUEUX = 'INFRUCTUEUX',
}

export enum MarketType {
  TRAVAUX = 'TRAVAUX',
  FOURNITURES = 'FOURNITURES',
  SERVICES = 'SERVICES',
  PRESTATIONS_INTELLECTUELLES = 'PRESTATIONS_INTELLECTUELLES',
}

export enum ProcurementMethod {
  APPEL_OFFRES_OUVERT = 'APPEL_OFFRES_OUVERT',
  APPEL_OFFRES_RESTREINT = 'APPEL_OFFRES_RESTREINT',
  GRE_A_GRE = 'GRE_A_GRE',
  DEMANDE_COTATION = 'DEMANDE_COTATION',
  CONSULTATION_RESTREINTE = 'CONSULTATION_RESTREINTE',
}

export enum SubmissionStatus {
  BROUILLON = 'BROUILLON',
  SOUMISE = 'SOUMISE',
  RECUE = 'RECUE',
  RETIREE = 'RETIREE',
  MODIFIEE = 'MODIFIEE',
  ACCEPTEE = 'ACCEPTEE',
  REJETEE = 'REJETEE',
}

export enum ContractStatus {
  BROUILLON = 'BROUILLON',
  EN_SIGNATURE = 'EN_SIGNATURE',
  SIGNE = 'SIGNE',
  APPROUVE = 'APPROUVE',
  NOTIFIE = 'NOTIFIE',
  EN_COURS = 'EN_COURS',
  TERMINE = 'TERMINE',
  RESILIE = 'RESILIE',
}

export enum PaymentRequestStatus {
  BROUILLON = 'BROUILLON',
  SOUMISE = 'SOUMISE',
  EN_VERIFICATION = 'EN_VERIFICATION',
  VALIDEE = 'VALIDEE',
  REJETEE = 'REJETEE',
  PAYEE = 'PAYEE',
}

export enum AppealType {
  RECOURS_GRACIEUX = 'RECOURS_GRACIEUX',
  RECOURS_HIERARCHIQUE = 'RECOURS_HIERARCHIQUE',
  RECOURS_JURIDICTIONNEL = 'RECOURS_JURIDICTIONNEL',
}

export enum AppealStatus {
  DEPOSE = 'DEPOSE',
  EN_INSTRUCTION = 'EN_INSTRUCTION',
  AUDIENCE = 'AUDIENCE',
  DECISION_RENDUE = 'DECISION_RENDUE',
  CLOTURE = 'CLOTURE',
}

export enum EvaluationStatus {
  EN_ATTENTE = 'EN_ATTENTE',
  OUVERTURE_PLIS = 'OUVERTURE_PLIS',
  EVALUATION_TECHNIQUE = 'EVALUATION_TECHNIQUE',
  EVALUATION_FINANCIERE = 'EVALUATION_FINANCIERE',
  ATTRIBUTION_PROVISOIRE = 'ATTRIBUTION_PROVISOIRE',
  TERMINEE = 'TERMINEE',
}

export enum ExecutionStatus {
  NON_DEMARRE = 'NON_DEMARRE',
  EN_COURS = 'EN_COURS',
  SUSPENDU = 'SUSPENDU',
  TERMINE = 'TERMINE',
  RECEPTION_PROVISOIRE = 'RECEPTION_PROVISOIRE',
  RECEPTION_DEFINITIVE = 'RECEPTION_DEFINITIVE',
}

export enum ForecastPlanStatus {
  BROUILLON = 'BROUILLON',
  SOUMIS = 'SOUMIS',
  VALIDE = 'VALIDE',
  PUBLIE = 'PUBLIE',
  REJETE = 'REJETE',
}
